// Archetype Template Vectors for Distance Calculation

export const ARCHETYPE_TEMPLATES = {
  "The Organizer": {
    "self-regulation": 90,
    "time-management": 95,
    "task-management": 90,
    "metacognitive-monitoring": 40,
    concentration: 30,
    "digital-literacy": 15,
    collaboration: -60,
    adaptability: -50,
    "note-taking": 95,
    retention: 85,
    "critical-thinking": -20,
    "well-being": -40,
  },
  "Deep Diver": {
    "self-regulation": 60,
    "time-management": -70,
    "task-management": -60,
    "metacognitive-monitoring": 75,
    concentration: 90,
    "digital-literacy": -10,
    collaboration: -40,
    adaptability: -50,
    "note-taking": 40,
    retention: 90,
    "critical-thinking": 95,
    "well-being": -40,
  },
  Collaborator: {
    "self-regulation": -60,
    "time-management": -50,
    "task-management": -60,
    "metacognitive-monitoring": -15,
    concentration: -40,
    "digital-literacy": 85,
    collaboration: 100,
    adaptability: 80,
    "note-taking": -40,
    retention: -20,
    "critical-thinking": 30,
    "well-being": 60,
  },
  "Adaptive Learner": {
    "self-regulation": 65,
    "time-management": -20,
    "task-management": -30,
    "metacognitive-monitoring": 50,
    concentration: -25,
    "digital-literacy": 90,
    collaboration: 70,
    adaptability: 100,
    "note-taking": -65,
    retention: -60,
    "critical-thinking": 80,
    "well-being": -30,
  },
  "Reflective Thinker": {
    "self-regulation": 70,
    "time-management": -65,
    "task-management": -70,
    "metacognitive-monitoring": 95,
    concentration: 75,
    "digital-literacy": -20,
    collaboration: -50,
    adaptability: -55,
    "note-taking": 20,
    retention: 80,
    "critical-thinking": 90,
    "well-being": 85,
  },
} as const

export type ArchetypeName = keyof typeof ARCHETYPE_TEMPLATES
